### ISSUE TITLE
Entrypoint issue when volume mounting /usr/local/lib/node_modules

### ISSUE THREAD

**Issue by anjunatl** [jesseditson/absolutize-links#1]
This is almost definitely more of a docker-related question than anything else, but I figure since you've been through this you're probably the best person to ask -

When I have `- /usr/local/lib/node_modules:/usr/local/lib/node_modules` in the `volumes` section of my service in my `docker-compose.yml`, I get `stat /usr/local/bin/npm: no such file or directory` - presumably from the `entrypoint` command

```
services:
  npm: &npm
    build: dev-env
    volumes:
      - .:/opt/project
      - /usr/local/lib/node_modules:/usr/local/lib/node_modules
    working_dir: /opt/project/app
    entrypoint: "/usr/local/bin/npm"
```

There is already a `/usr/local/lib/node_modules` in the docker container, and `/usr/local/bin/npm` exists in the container, so I don't know why I'm getting that error.

```
root@c584d87f976a:/# cd /usr/local/lib/node_modules/
root@c584d87f976a:/usr/local/lib/node_modules# ls
gulp  npm
root@c584d87f976a:/usr/local/lib/node_modules# cd ../../bin/
root@c584d87f976a:/usr/local/bin# ls
gulp  node  nodejs  npm  yarn  yarnpkg
root@c584d87f976a:/usr/local/bin#
```

And on my host machine (Mac), I've got `/usr/local/lib/node_modules`

```
➜  node_modules pwd
/usr/local/lib/node_modules
```

I'm not sure why I'd be getting that, especially since the entrypoint is in `/usr/local/bin` and the volume mount is for `/usr/local/lib`.

Any help would be appreciated - thanks!
